let mapleader = ","
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
filetype plugin on
filetype plugin indent on
set ignorecase
set smartcase
set nomodeline
set cursorline

nnoremap <leader>s :%s/
vnoremap <leader>c "*y
nnoremap <leader>c "*y
nnoremap <leader>v "*p
vnoremap <leader>v "*p
nnoremap <silent> ,/ :noh<cr>
nnoremap <silent> ,, :b#<cr>
nmap <c-o> o<esc>xk
nmap <c-i> O<esc>xj

"set relativenumber
set number

if exists('&inccommand')
  set inccommand=split
endif

" Split Switching
if has('nvim')
  tnoremap <c-]> <C-\><C-n>
  tnoremap <c-h> <c-\><c-n><c-w>h
  tnoremap <c-j> <c-\><c-n><c-w>j
  tnoremap <c-k> <c-\><c-n><c-w>k
  tnoremap <c-l> <c-\><c-n><c-w>l
  nnoremap <c-h> <c-w>h
  nnoremap <c-j> <c-w>j
  nnoremap <c-k> <c-w>k
  nnoremap <c-l> <c-w>l
endif


" Minpac Plugins
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
  command! PackUpdate call minpac#update()
  command! PackClean call minpac#clean()

call minpac#add('tpope/vim-surround')

call minpac#add('machakann/vim-highlightedyank')

call minpac#add('tpope/vim-sensible')
  if has('nvim')
    let g:loaded_sensible=0
  endif

" call minpac#add('ctrlpvim/ctrlp.vim')
"   nnoremap <C-f> :CtrlP<CR>
"   set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
"   let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

call minpac#add('wincent/command-t')

call minpac#add('kassio/neoterm')
  let g:neoterm_position='vertical'
  " hide/close terminal
  nnoremap <silent> ,nt :Ttoggle<cr>
  " clear terminal
  nnoremap <silent> ,nc :T clear<cr>
  " kills the current job (send a <c-c>)
  nnoremap <silent> ,nk :Tclose!<cr>

call minpac#add('janko-m/vim-test')
  let test#strategy = "neoterm"
  nmap <silent> <leader>t :TestFile<CR>
  nmap <silent> <leader>T :TestNearest<CR>
  nmap <silent> <leader>a :TestSuite<CR>
  nmap <silent> <leader>l :TestLast<CR>
  nmap <silent> <leader>g :TestVisit<CR>

call minpac#add('jiangmiao/auto-pairs')

call minpac#add('scrooloose/nerdtree')
  nnoremap <leader>nn :NERDTreeToggle<CR>
  nnoremap <leader>nf :NERDTreeFind<CR>

call minpac#add('Xuyuanp/nerdtree-git-plugin')

call minpac#add('jlanzarotta/bufexplorer')
  " switch to prev buffer and delete buffer
  " switched from. kill the buffer, not the split
  nnoremap <leader>bb :ToggleBufExplorer<CR>
  nnoremap <leader>bd :b#<bar>bd#<CR>

call minpac#add('tpope/vim-commentary')
call minpac#add('tpope/vim-rails')
call minpac#add('tpope/vim-endwise')

" Colors..............................................................
syntax on
set termguicolors

call minpac#add('dracula/vim', {'type': 'opt'})
  " color dracula
call minpac#add('icymind/NeoSolarized', {'type': 'opt'})
  " let g:neosolarized_contrast="high"
  " let g:neosolarized_visibility="high"
  " let g:neosolarized_termtrans=1
  " let g:neosolarized_bold=1
  " let g:neosolarized_underline=1
  " let g:neosolarized_italic=1
  " set background=dark
  " color NeoSolarized
call minpac#add('jacoborus/tender.vim', {'type': 'opt'})
call minpac#add('rakr/vim-one', {'type': 'opt'})
  " set background=dark
  " let g:one_allow_italics = 1
  " color one
call minpac#add('KeitaNakamura/neodark.vim', {'type': 'opt'})
  " let g:neodark#background = '#1B202A'
  " let g:neodark#solid_vertsplit = 1
  " let g:neodark#use_custom_terminal_theme = 0
  " colorscheme neodark
  
" call minpac#add('tyrannicaltoucan/vim-deep-space', {'type': 'opt'}) "***********
  " let g:deepspace_italics=1
  " colorscheme deep-space

call minpac#add('bdtomlin/vim-deep-space', {'type': 'opt'}) "***********
  let g:deepspace_italics=1
  colorscheme deep-space

call minpac#add('christophermca/meta5', {'type': 'opt'})
  " colorscheme meta5

call minpac#add('whatyouhide/vim-gotham', {'type': 'opt'})
  " colorscheme gotham

call minpac#add('gosukiwi/vim-atom-dark', {'type': 'opt'})
  " colorscheme onehalfdark

call minpac#add('jakwings/vim-colors', {'type': 'opt'})
  " colorscheme garden
  " colorscheme messy
  " colorscheme moody

call minpac#add('nightsense/seabird', {'type': 'opt'})
  " colorscheme petrel

call minpac#add('tyrannicaltoucan/vim-quantum', {'type': 'opt'})
  " let g:quantum_black=1
  " let g:quantum_italics=1
  " let g:airline_theme='quantum'
  " set background=dark
  " colorscheme quantum

call minpac#add('rakr/vim-two-firewatch', {'type': 'opt'})
  " set background=dark
  " colorscheme quantum
